// <auto-generated />
namespace WebDACS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update3003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update3003));
        
        string IMigrationMetadata.Id
        {
            get { return "202303300904214_Update3003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
